var general=[
    "Dictionary",
    "House",
    "School",
    "Bank",
    "Gym",
    "Spa",
    "Garage",
    "Spaceship",
    "Tomorrow",
    "Jar",
    "Mall",
    "Credit card",
    "Wire",
    "Electricity",
    "Grill",
    "Bathroom scale",
    "Spider web",
    "Hill",
    "Protest",
    "Question",
    "Spoon",
    "Lawyer",
    "Manager",
    "Silk",
    "Homework",
    "Earthquake",
    "Thunder",
    "Customer",
    "Factory",
    "Car",
    "Van",
    "School bus",
    "Airplane",
    "Ship",
    "Cruise ship",
    "Ocean",
    "Air",
    "Fire",
    "Chocolate",
    "Shaving cream",
    "Ice cube",
    "The nazis",
    "Planet Earth",
    "Sun",
    "Moon",
    "Solar system",
    "Black hole",
    "Relativity",
    "Albert Einstein",
    "Basketball",
    "Football",
    "Dance",
    "Pizza",
    "Salon",
    "Bedroom",
    "Bed",
    "Fridge",
    "Bottle",
    "Cup",
    "Fish",
    "Water",
    "Mango",
    "Trash",
    "Roof",
    "Sunset",
    "Sunrise",
    "Picture frame",
    "Wheelchair",
    "Chef",
    "Newspaper",
    "Marathon",
    "Strawberry",
    "Fruit",
    "Blue",
    "Transparent",
    "Happiness",
    "Museum",
    "Painting",
    "Wall",
    "Door",
    "Finger",
    "Finger nail",
    "Nipple",
    "Hair",
    "Pants",
    "T-Shirt",
    "Scarf",
    "Greek God",
    "Europe",
    "Africa",
    "Antarctica",
    "Bear",
    "Pear",
    "Lemonade",
    "Hair clip",
    "Spongebob",
    "Cross",
    "Church",
    "Religion",
    "Classroom",
    "Whale",
    "Door knob",
    "Poster",
    "Ostrich",
    "Octopus",
    "Air Conditioner",
    "Lamp",
    "Dog",
    "Snake",
    "Dress",
    "High heels",
    "Snow boots",
    "Snow",
    "Rain",
    "Wind",
    "Cloud",
    "Horse",
    "Metal chain",
    "Laptop",
    "Cigarette",
    "Face mask",
    "Heart",
    "Lung",
    "Cushion",
    "Acne",
    "Eye",
    "Eye lashes",
    "Wood",
    "Plastic",
    "Diamond",
    "Gold",
    "Metal",
    "Biology",
    "Chemistry",
    "Math",
    "History",
    "Teacher",
    "Medicine",
    "Illness",
    "Button",
    "Middle East",
    "Asia",
    "USA",
    "Canada",
    "Mexico",
    "Tacos",
    "Ant",
    "Stairs",
    "Tattoo",
    "Hair dye",
    "Necklace",
    "Bee",
    "Street",
    "Mount Everest",
    "Nuclear bomb",
    "Potato",
    "Swimming pool",
    "Treadmill",
    "Hotel",
    "Zumba",
    "Karaoke",
    "Ballet",
    "Lipstick",
    "Helmet",
    "Sword",
    "Remote Control",
    "Netflix",
    "Instagram",
    "Pewdiepie",
    "Fortnite",
    "Vodka",
    "Orange juice",
    "Milk",
    "Cereal",
    "Movie",
    "Spiderman",
    "Volcano",
    "Mountain",
    "Music",
    "Camera",
    "Radio",
    "Telescope",
    "Microscope",
    "Bacteria",
    "Soap",
    "Hair comb",
    "Toothbrush",
    "Shampoo",
    "Whisky",
    "Cat",
    "Tail",
    "Bootstrap",
    "Piano",
    "Guitar",
    "Chair",
    "Pub",
    "Wedding",
    "Break up",
    "Ring",
    "Eyebrows",
    "Elephant",
    "Saudi Arabia",
    "Syria",
    "China",
    "Senegal",
    "Zimbabwe",
    "Venezuela",
    "Qatar",
    "Your loud neighbours",
    "River",
    "Giraffe",
    "TV",
    "Dirty Laundry",
    "Monkey",
    "The flu",
    "Astronaut",
    "FireFighter",
    "Actor",
    "Book",
    "Art",
    "Ice Cream",
    "Scrabble",
    "Computer",
    "Meat",
    "Law",
    "Economics",
    "Love",
    "Internet",
    "Science",
    "Boyfriend",
    "Girlfriend",
    "Best friend",
    "Child",
    "News",
    "Night",
    "Fishing",
    "Politician",
    "Drug Dealer",
    "Woman",
    "Man",
    "Death",
    "Airport",
    "Airplane",
    "Seatbelt",
    "Honey",
    "BBQ sauce",
    "Mustard",
    "Mayonnaise",
    "Truck",
    "Salad",
    "Tongue",
    "Funeral",
    "Pizza",
    "Shirt",
    "Uncle",
    "Poetry",
    "Butter",
    "Butterfly",
    "Bathroom",
    "Parking",
    "The number 9",
    "Brain",
    "Oil",
    "Table",
    "Christmas",
    "Halloween",
    "Witch",
    "Ghost",
    "Zombie",
    "Easter",
    "Eid el Adha",
    "Muscle",
    "Vegetable",
    "Party",
    "Winter",
    "Autumn",
    "Summer",
    "Spring",
    "Finger",
    "Meeting",
    "Lie",
    "Wine",
    "India",
    "Dust",
    "Email",
    "Salary",
    "Closet",
    "Angel",
    "Devil",
    "God",
    "Sandwich",
    "Bicycle",
    "Concert",
    "Cow",
    "Island",
    "Leg",
    "Lip",
    "Pen",
    "Paper",
    "The Twin Towers",
    "Feminism", 
    "Chernobyl",
    "Popcorn",

]
var culture=[
    "Van Gogh",
    "Plato",
    "Lavoisier",
    "The Thinker statue",
    "Beyonce",
    "Drake",
    "Ariana Grande",
    "Steve Jobs",
    "Bill Gates",
    "Elon Musk",
    "Breaking Bad",
    "Jeff Bezos",
    "Marie Curie",
    "Picasso",
    "World war II",
    "Buddha",
    "Jesus",
    "Adolph Hitler",
    "Jackie Chan",
    "The Ottomans",
    "Ancient Greece",
    "Eiffel Tour",
    "Burj Khalifa",
    "Monopoly",
    "The Monalisa",
    "Gangnam Style",
    "Barack Obama", 
    "Eminem",
    "Marylin Monroe",
    "The Louvre",
    "The Queen of England",
    "Emmanuel Macron",
    "The Kardashians",
    "Taylor Swift",
    "Arctic Monkeys",
    "Angelina Jolie",
    "George Clooney"
]
var lebanese=[
    "El Dahye",
    "Falafel",
    "Lebanon",
    "Haifa Wehbe",
    "Fadi El Khatib",
    "Dabke",
    "Arak",
    "Kebbe",
    "Beirut",
    "Hezbullah",
    "Mia Khalifa",
    "Haraket Amal",
    "Ashrafiye",
    "Chere3 el Hamra",
    "Chocolate Knefe",
    "Mjaddara",
    "Tabboule",
    "Ouwet",
    "Awniye",
    "Birthday crown taba3 Burger King",
    "Lebanese University",
    "Tlemiz roumieh",
    "Bonjus haram", 
    "Espace 2000",
    "Rio Lento",
    "Makhfar Hbeich",
    "Kaak Abou Arab",
    "Bachir Ice Cream",
    "Mjaddara", 
    "Hommos", 
    "Abeille d'or",
    "Mariam Nour", 
    "Myriam Klink",
    "Mar Charbel",
    "Man'ouche",
    "Labne",
    "Faraya",
    "Jbeil",
    "Jagal el USEK",
    "Sabah",
    "LAU",
    "AUB",
    "Fairouz",
    "Ali el Deek",
    "Manchar ghassil",
    "El jalyet",
    "Michel Aoun",
    "Nabih Berri",
    "Bashar El Assad",
    "The 'w atyab' ad",
    "The Lebanese Revolution",
    "The Lebanese Civil War",
]

var data = [general, culture, lebanese]
