var dictionary=[
    "dictionary",
    "Lebanon",
    "House",
    "School",
    "Bank",
    "Gym",
    "Spa",
    "Garage",
    "Spaceship",
    "Car",
    "Van",
    "School bus",
    "Airplane",
    "Ship",
    "Cruise ship",
    "Ocean",
    "Air",
    "Fire",
    "Planet Earth",
    "Sun",
    "Moon",
    "Solar system",
    "Black hole",
    "Relativity",
    "Albert Einstein",
    "Haifa Wehbe",
    "Fadi El Khatib",
    "Basketball",
    "Football",
    "Dance",
    "Dabke",
    "Arak",
    "Pizza",
    "Kebbe",
    "Salon",
    "Bedroom",
    "Bed",
    "Fridge",
    "Bottle",
    "Cup",
    "Fish",
    "Water",
    "Mango",
    "Strawberry",
    "Fruit",
    "Blue",
    "Transparent",
    "Happiness",
    "Beirut",
    "Hezbullah",
    "Mia Khalifa",
    "Beyonce",
    "Marie Curie",
    "Picasso",
    "Museum",
    "Painting",
    "Wall",
    "Door",
    "Finger",
    "Finger nail",
    "Nipple",
    "Hair",
    "Pants",
    "T-Shirt",
    "Scarf",
    "Greek God",
    "Europe",
    "Africa",
    "Antarctica",
    "Bear",
    "Pear",
    "Lemonade",
    "Hair clip",
    "Spongebob",
    "Cross",
    "Church",
    "Religion",
    "Classroom",
    "Whale",
    "Door knob",
    "Poster",
    "Ostrich",
    "Octopus",
    "Air Conditioner",
    "Lamp",
    "Dog",
    "Snake",
    "Monopoly",
    "Dress",
    "High heels",
    "Snow boots",
    "Snow",
    "Rain",
    "Wind",
    "Cloud",
    "Horse",
    "Metal chain",
    "Laptop",
    "Cigarette",
    "Face mask",
    "Heart",
    "Lung",
    "Cushion",
    "Acne",
    "Eye",
    "Eye lashes",
    "Wood",
    "Plastic",
    "Diamond",
    "Gold",
    "Metal",
    "Biology",
    "Chemistry",
    "Math",
    "History",
    "Teacher",
    "Medicine",
    "Illness",
    "Button",
    "Middle East",
    "Asia",
    "USA",
    "Canada",
    "Mexico",
    "Tacos",
    "Mjaddara",
    "Tabboule",
    "Ant",
    "Stairs",
    "Tattoo",
    "Hair dye",
    "Necklace",
    "Bee",
    "Street",
    "Eiffel tour",
    "Burj Khalifa",
    "Falafel",
    "Mount Everest",
    "Nuclear bomb",
    "World war II",
    "Adolph Hitler",
    "Angelina Jolie",
    "Potato",
    "Swimming pool",
    "Treadmill",
    "Kaak Abou Arab",
    "Bachir Ice Cream",
    "Abeille d'or",
    "Man'ouche",
    "Hotel",
    "Zumba",
    "Karaoke",
    "Labne",
    "Ballet",
    "Lipstick",
    "Helmet",
    "Sword",
    "Remote Control",
    "Netflix",
    "Instagram",
    "Pewdiepie",
    "Fortnite",
    "Lebanese University",
    "Tlemiz roumieh",
    "Makhfar Hbeich",
    "Vodka",
    "Orange juice",
    "Milk",
    "Cereal",
    "Movie",
    "Spiderman",
    "Volcano",
    "Mountain",
    "Faraya",
    "Jbeil",
    "Jagal el USEK",
    "LAU",
    "AUB",
    "Najatte",
    "Habib",
    "The Monalisa",
    "Gangnam Style",
    "Music",
    "Camera",
    "Radio",
    "Telescope",
    "Microscope",
    "Bacteria",
    "Soap",
    "Hair comb",
    "Toothbrush",
    "Shampoo",
    "Whisky",
    "Cat",
    "Tail",
    "Bootstrap",
    "Piano",
    "Guitar",
    "Chair",
    "Pub",
    "Wedding",
    "Break up",
    "Ring",
    "Eyebrows",
    "Elephant",
    "Saudi Arabia",
    "Syria",
    "China",
    "Senegal",
    "Zimbabwe",
    "Venezuela",
    "Qatar",
    "Emmanuel Macron",
    "Fairouz",
    "Ali el Deek",
    "Your loud neighbours",
    "Christian",
    "Rita",
    "Chady",
    "Sandy",
    "Jane",
    "Elie",
    "River",
    "Giraffe",
    "TV",
    "Dirty Laundry",
    "Manchar ghassil",
    "El jalyet",
    "Monkey",
    "The flu",
    "Astronaut",
    "FireFighter",
    "Actor",
    "Book",
    "Art",
    "Ice Cream",
    "Scrabble",
    "Computer",
    "Meat",
    "Law",
    "Economics",
    "Love",
    "Internet",
    "Science",
    "Boyfriend",
    "Girlfriend",
    "Best friend",
    "Child",
    "News",
    "Night",
    "Fishing",
    "Politician",
    "Michel Aoun",
    "Nabih Berri",
    "Bashar El Assad",
    "Drug Dealer",
    "Woman",
    "Man",
    "Death",
    "The 'w atyab' ad",
    "The Queen of England",
    "Airport",
    "Airplane",
    "Seatbelt",
    "The Lebanese Revolution",
    "The Lebanese Civil War",
    "Honey",
    "BBQ sauce",
    "Mustard",
    "Mayonnaise",
    "Truck",
    "Salad",
    "Tongue",
    "Funeral",
    "Pizza",
    "Shirt",
    "Uncle",
    "Poetry",
    "Butter",
    "Butterfly",
    "Bathroom",
    "Parking",
    "The number 9",
    "Brain",
    "Oil",
    "The Kardashians",
    "Table",
    "Christmas",
    "Halloween",
    "Witch",
    "Ghost",
    "Zombie",
    "Easter",
    "Eid el Adha",
    "Birthday crowns taba3 Burger King",
    "Muscle",
    "Vegetable",
    "Party",
    "Winter",
    "Autumn",
    "Summer",
    "Spring",
    "Finger",
    "Meeting",
    "Lie",
    "Wine",
    "The Ottomans",
    "Ancient Greece",
    "India",
    "Dust",
    "Email",
    "Salary",
    "Closet",
    "Angel",
    "Devil",
    "God",
    "Eminem",
    "Marylin Monroe",
    "Sandwich",
    "Bicycle",
    "Concert",
    "Cow",
    "Island",
    "Leg",
    "Lip",
    "Pen",
    "Paper",
    "The Twin Towers",
    "Barack Obama", "Mariam Nour", "Myriam Klink",
    "Feminism", "Bonjus haram", "El Dahye",
    "Chernobyl", "Mjaddara", "Hommos", "Popcorn","Mar Charbel"

]
